apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    local:
        push: false
    artifacts :
      - image: nivedpk/clients
        context: clients
        docker:
            dockerfile: Dockerfile
        sync:
            manual:
              - src: 'src/**/*.js'
                dest: .
      - image: nivedpk/comments
        context: comments
        docker:
            dockerfile: Dockerfile
        sync:
            manual:
              - src: '*.js'
                dest: .
      - image: nivedpk/event-bus
        context: event-bus
        docker:
            dockerfile: Dockerfile
        sync:
            manual:
              - src: '*.js'
                dest: .
      - image: nivedpk/moderation
        context: moderation
        docker:
            dockerfile: Dockerfile
        sync:
            manual:
              - src: '*.js'
                dest: .
      - image: nivedpk/posts
        context: posts
        docker:
            dockerfile: Dockerfile
        sync:
            manual:
              - src: '*.js'
                dest: .
      - image: nivedpk/query
        context: query
        docker:
            dockerfile: Dockerfile
        sync:
            manual:
              - src: '*.js'
                dest: .